In [52]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [53]:
import seaborn as sns
import seaborn.matrix as smatrix

In [54]:
data_df = pd.read_csv("titanic.csv")
data_df.head()
data_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [55]:
data_df.columns
data_df.dtypes
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [56]:
data_df['Fare'] = data_df['Fare'].astype(int)

In [57]:
cols = ['SibSp','Parch','Ticket']
data_df = data_df.drop(cols, axis=1)

In [58]:
def replace_Sex(val):
    if val == "female":
        return 0
    else:
        return 1
    
data_df['Sex'] = data_df['Sex'].apply(replace_Sex, 1)

/var/folders/kq/22rtshv9635518wrmfbx3l1r0000gn/T/ipykernel_65564/2960743763.py:7: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  data_df['Sex'] = data_df['Sex'].apply(replace_Sex, 1)

In [59]:
data_df['Embarked'].mask(data_df['Embarked'] == 'C', 'Cherbourg', inplace=True)
data_df['Embarked'].mask(data_df['Embarked'] == 'S', 'Southhampton', inplace=True)
data_df['Embarked'].mask(data_df['Embarked'] == 'Q', 'Queenstown', inplace=True)

data_df.head()

/var/folders/kq/22rtshv9635518wrmfbx3l1r0000gn/T/ipykernel_65564/4145910887.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_df['Embarked'].mask(data_df['Embarked'] == 'C', 'Cherbourg', inplace=True)
/var/folders/kq/22rtshv9635518wrmfbx3l1r0000gn/T/ipykernel_65564/4145910887.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_df['Embarked'].mask(data_df['Embarked'] == 'S', 'Southhampton', inplace=True)
/var/folders/kq/22rtshv9635518wrmfbx3l1r0000gn/T/ipykernel_65564/4145910887.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_df['Embarked'].mask(data_df['Embarked'] == 'Q', 'Queenstown', inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,7,NaN,Southhampton
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,71,C85,Cherbourg
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,7,NaN,Southhampton
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,53,C123,Southhampton
4,5,0,3,"Allen, Mr. William Henry",1,35.0,8,NaN,Southhampton

In [60]:
correlation = data_df.corr()
sns.heatmap(correlation, annot=True)

ValueError: could not convert string to float: 'Braund, Mr. Owen Harris'

In [ ]:
import seaborn as sns
from sklearn.model_selection import train_test_split

In [64]:
data_df['Fare'].fillna(data_df['Fare'].mean(), inplace=True)
data_df['Pclass'].fillna(data_df['Pclass'].mean(), inplace=True)
data_df['Age'].fillna(data_df['Age'].mean(), inplace=True)

/var/folders/kq/22rtshv9635518wrmfbx3l1r0000gn/T/ipykernel_65564/189228641.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_df['Fare'].fillna(data_df['Fare'].mean(), inplace=True)
/var/folders/kq/22rtshv9635518wrmfbx3l1r0000gn/T/ipykernel_65564/189228641.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_df['Pclass'].fillna(data_df['Pclass'].mean(), inplace=True)
/var/folders/kq/22rtshv9635518wrmfbx3l1r0000gn/T/ipykernel_65564/189228641.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_df['Age'].fillna(data_df['Age'].mean(), inplace=True)

In [65]:
X = data_df[['Fare','Pclass','Age']]
y = data_df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=32)

In [70]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
regression = LogisticRegression()
regression.fit(X_train, y_train)

LogisticRegression()

In [71]:
y_pred = regression.predict(X_test)
y_pred

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0])

In [72]:
accuracy_score = regression.score(X_test, y_test)
accuracy_score

0.7052238805970149

In [ ]:
# I used logistic regression due to us working with a yes/no or dichotomous question.